Repository HypothesisWorks/hypothesis, pull requests merged in 2018-12, with the labels that each got.

#1682 Change the voting example to use permutations
  CONTRIBUTING.rst
  hypothesis-python/docs/examples.rst
Labels: docs

#1663 Use new Hypothesis trove classifier!
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/setup.py
Labels: docs, meta

#1669 Fix ceil and floor for Numpy ints on Py3
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/numpy/test_narrow_floats.py
Labels: bug

#1577 Fix statistics reporting when running under pytest-xdist
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/pytest/test_statistics.py
Labels: enhancement

#1666 Warn on strategies collected as tests
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/pytest/test_capture.py
Labels: legibility

#1687 #1685: extend the set of types returned from from_type(type)
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
Labels: enhancement

#1609 New given-based backend for stateful tests
  .isort.cfg
  .travis.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: enhancement

#1698 Track deprecation information with 'since' internally
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/extra/datetime.py
  hypothesis-python/src/hypothesis/extra/fakefactory.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/renaming.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_renaming.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/nocover/test_regressions.py
Labels: legibility

#1616 Improve shrinking of integers() with one bound
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/searchstrategy/datetime.py
  hypothesis-python/src/hypothesis/searchstrategy/numbers.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_conjecture_utils.py
  hypothesis-python/tests/cover/test_slippage.py
Labels: shrink-quality

#1716 Add API to remove items from stateful.Bundle
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: enhancement

#1701 Don't error on a Lambda in a line with Unicode identifiers
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/py3/test_unicode_identifiers.py
Labels: bug

#1721 Change how the alphabet minimize step works
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
Labels: shrink-quality
