Repository HypothesisWorks/hypothesis, pull requests merged in 2018-09, with the labels that each got.

#1575 Run Sphinx in nitpick mode, fix broken cross-references
  .gitignore
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/django.rst
  hypothesis-python/docs/healthchecks.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/strategies.py
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
  whole-repo-tests/test_rst_is_valid.py
Labels: docs

#1590 use require_relative, so the code can be required from anywhere
  hypothesis-ruby/RELEASE.md
  hypothesis-ruby/lib/hypothesis.rb
  hypothesis-ruby/lib/hypothesis/engine.rb
Labels: language: Ruby

#1572 Make assigning attributes of the settings class an error
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/tests/cover/test_settings.py
Labels: legibility

#1595 Fix internal error in recursive()
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/tests/cover/test_recursive.py
Labels: bug

#1610 Fix deprecation warning stacklevel
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/tests/nocover/test_regressions.py
Labels: legibility
