Repository HypothesisWorks/hypothesis, pull requests merged in 2018-10, with the labels that each got.

#1603 Consolidate prechecks for faster Travis runs
  .travis.yml
  tooling/src/hypothesistooling/__main__.py
  whole-repo-tests/test_documentation.py
  whole-repo-tests/test_requirements.py
Labels: tests/build/CI

#1611 Document mock.patch interaction, fix links
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/endorsements.rst
  hypothesis-python/docs/examples.rst
  hypothesis-python/docs/index.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/docs/reproducing.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/README.rst
  hypothesis-python/tests/pandas/test_data_frame.py
  hypothesis-python/tests/py3/test_mock.py
  hypothesis-python/tests/pytest/test_capture.py
Labels: docs

#1623 Fix pip-tools version
  requirements/tools.txt
Labels: tests/build/CI

#1627 Use flake8-alfred to forbid use of bytes()
  .flake8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/fakefactory.py
  hypothesis-python/src/hypothesis/reporting.py
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
  hypothesis-python/tests/numpy/test_gen_data.py
  requirements/tools.in
  requirements/tools.txt
Labels: tests/build/CI

#1626 min_size arguments default to 0
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_validation.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
Labels: legibility

#1607 Avoid caching internal strategy that has a reference to the test class
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/nocover/test_cacheable.py
Labels: bug

#1634 Deprecated inexact values for integers, floats and fractions
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/nocover/test_simple_numbers.py
Labels: legibility

#1633 Add verbosity options for pytest
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
Labels: enhancement

#1645 Added more types to that can be detected hypothesis.infer
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
Labels: enhancement

#1582 Elide internal frames from tracebacks, to focus on user code
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_escalation.py
Labels: legibility

#1653 Shrink errors from pytest.fail() in given, not just stateful testing
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_core.py
Labels: bug

#1592 Check that numpy can represent complex64/unicode/bytestring elements
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: legibility

#1652 Update pass name in internal docs
  CONTRIBUTING.rst
  guides/internals.rst
Labels: docs

#1659 Add explicit error for assigning to settings attribute of state machine
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_settings.py
Labels: legibility

#1657 Fix from_type on Python 2
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/py2/test_from_type.py
Labels: bug
