Repository HypothesisWorks/hypothesis, pull requests merged in 2019-06, with the labels that each got.

#2003 Reliably cover the handling of stale example identifiers while shrinking
  hypothesis-python/tests/cover/test_conjecture_engine.py
Labels: flaky-tests, tests/build/CI

#2000 Fix spurious TypeError with a composite having keyword-only arguments.
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/py3/test_composite_kwonlyargs.py
Labels: bug

#2004 Explicitly name deprecated methods in note
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/models.py
Labels: legibility

#2005 Use CodeType.replace in Python 3.8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/pandas/test_indexes.py
Labels: interop

#2015 Support newer typing backport too
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  requirements/typing.txt
Labels: bug, interop

#2016 Cleaner tracebacks for broken strategies
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
Labels: legibility

#2023 Preclude .jpg, .png, .gif being rewritten on git push
  .gitattributes
Labels: meta

#1998 Consolidate CI platforms
  .circleci/config.yml
  appveyor.yml
  hypothesis-python/docs/supported.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/projects/hypothesispython.py
Labels: tests/build/CI

#2001 Fix day-of-month overflow in datetimes()
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/datetime.py
  hypothesis-python/tests/cover/test_datetimes.py
  hypothesis-python/tests/cover/test_verbosity.py
Labels: performance

#1993 Port `minimal()` test helper from `find()` to `@given`
  hypothesis-python/tests/common/debug.py
  hypothesis-python/tests/cover/test_datetimes.py
  hypothesis-python/tests/cover/test_numerics.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/cover/test_simple_strings.py
  hypothesis-python/tests/cover/test_slices.py
  hypothesis-python/tests/cover/test_verbosity.py
  hypothesis-python/tests/nocover/test_collective_minimization.py
  hypothesis-python/tests/nocover/test_flatmap.py
  hypothesis-python/tests/nocover/test_recursive.py
  hypothesis-python/tests/nocover/test_sets.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/pandas/test_data_frame.py
  hypothesis-python/tests/quality/test_float_shrinking.py
  hypothesis-python/tests/quality/test_shrink_quality.py
  hypothesis-python/tox.ini
Labels: legibility, tests/build/CI

#2026 Make shellcheck install much faster
  tooling/src/hypothesistooling/installers.py
  whole-repo-tests/test_shellcheck.py
Labels: tests/build/CI
