Repository HypothesisWorks/hypothesis, pull requests merged in 2019-01, with the labels that each got.

#1720 Fix floats() disallowed generation of infinity and bad error message
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/internal/conjecture/floats.py
  hypothesis-python/src/hypothesis/searchstrategy/numbers.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_float_nastiness.py
Labels: bug, legibility

#1735 Fix reference rendering to `hypothesis.strategies.randoms` in docs
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
Labels: docs

#1730 Handle errors that occur once a data object is already frozen
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_error_in_draw.py
  hypothesis-python/tests/cover/test_intervalset.py
Labels: bug

#1736 Add url strategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/tests/cover/test_provisional_strategies.py
  hypothesis-python/tests/django/toystore/models.py
Labels: enhancement

#1745 Detect potential overflows in cached_test_function
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/nocover/test_conjecture_engine.py
Labels: performance, shrink-quality

#1743 Clean up extra.django namespace and improve consistency with core
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/django.rst
  hypothesis-python/src/hypothesis/extra/django/__init__.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/django/toystore/test_given_models.py
Labels: legibility

#1723 Add multiple items to a bundle
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: enhancement

#1752 Factor out tree logic from ConjectureRunner
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/nocover/test_conjecture_engine.py
Labels: test-case-reduction

#1751 Iterate over block pairs in a different order.
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/nocover/test_conjecture_engine.py
Labels: test-case-reduction

#1763 Fix pytest30 compat build
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1757 Randomize order of alphabet normalization
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Labels: test-case-reduction

#1766 Misc docs cleanup
  hypothesis-python/docs/database.rst
  hypothesis-python/docs/development.rst
  hypothesis-python/docs/examples.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/docs/supported.rst
Labels: docs

#1754 Consistent distribution of integers()
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/tests/nocover/test_integer_ranges.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement

#1756 Improve internal shrinker documentation
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Labels: docs, test-case-reduction

#1771 Fix broken build (check_requirements) on master
  whole-repo-tests/test_requirements.py
Labels: tests/build/CI

#1772 Patch cathetus floating-point imprecision which broke complex_numbers
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/internal/cathetus.py
  hypothesis-python/tests/cover/test_cathetus.py
Labels: bug

#1740 Create strategies for strings matching Lark (EBNF) context-free grammars
  .isort.cfg
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/tests/README.rst
  hypothesis-python/tests/lark/__init__.py
  hypothesis-python/tests/lark/test_grammar.py
  hypothesis-python/tests/py2/test_validation.py
  hypothesis-python/tox.ini
  requirements/coverage.in
  requirements/coverage.txt
  requirements/tools.in
  requirements/tools.txt
Labels: new-feature

#1773 Deprecate and disable hung_test healthcheck
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_deadline.py
  hypothesis-python/tests/cover/test_health_checks.py
Labels: enhancement

#1761 Django form generation
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/django.rst
  hypothesis-python/src/hypothesis/extra/django/__init__.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/tests/django/toystore/forms.py
  hypothesis-python/tests/django/toystore/test_given_forms.py
Labels: new-feature

#1767 Don't store the entire ConjectureData object in the tree
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/cache.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/cover/test_cache_implementation.py
  hypothesis-python/tests/cover/test_conjecture_data_tree.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/nocover/test_cache_implementation.py
Labels: performance
