Repository HypothesisWorks/hypothesis, pull requests merged in 2019-07, with the labels that each got.

#1992 Deprecate the buffer_size setting
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
Labels: legibility

#2019 Adds strategy for advanced indexing with integer-arrays
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
Labels: new-feature

#2038 Fix warnings in Pandas extra
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
Labels: legibility

#2025 Implement `s.example()` in terms of `@given`, not `find()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_deferred_strategies.py
  hypothesis-python/tests/cover/test_example.py
  hypothesis-python/tests/cover/test_functions.py
  hypothesis-python/tests/cover/test_slices.py
  hypothesis-python/tests/nocover/test_regressions.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/pandas/test_indexes.py
  hypothesis-python/tests/py3/test_lookup.py
  hypothesis-python/tox.ini
Labels: legibility

#2041 Deprecate find()
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_arbitrary_data.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_random_module.py
  hypothesis-python/tests/cover/test_runner_strategy.py
  hypothesis-python/tests/cover/test_validation.py
  hypothesis-python/tests/cover/test_verbosity.py
  hypothesis-python/tests/nocover/test_boundary_exploration.py
  hypothesis-python/tests/nocover/test_database_usage.py
  hypothesis-python/tests/nocover/test_deferred_errors.py
  hypothesis-python/tests/nocover/test_find.py
  hypothesis-python/tests/nocover/test_imports.py
  hypothesis-python/tests/nocover/test_randomization.py
  hypothesis-python/tests/py2/test_generate_ints.py
Labels: legibility

#2042 Delete appveyor.yml
  appveyor.yml
Labels: tests/build/CI

#2044 Pass alphabet through to characters()
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_simple_strings.py
Labels: enhancement

#2047 fix mock imports for py3
  CONTRIBUTING.rst
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/cover/test_regressions.py
  hypothesis-python/tests/cover/test_statistical_events.py
  hypothesis-python/tests/pytest/test_fixtures.py
  requirements/test.in
  requirements/test.txt
  requirements/tools.in
  requirements/tools.txt
Labels: tests/build/CI

#2049 Detect and warn on float truncation in arrays
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/cover/test_numerics.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/numpy/test_narrow_floats.py
Labels: bug, legibility

#2059 Restore stable reprs across multiple processes in test_direct_strategies.py
  hypothesis-python/tests/cover/test_direct_strategies.py
Labels: tests/build/CI
