Repository HypothesisWorks/hypothesis, pull requests merged in 2019-08, with the labels that each got.

#2063 Faster build on Azure Pipelines
  azure-pipelines.yml
  build.sh
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2058 Clarify settings reprs and refactor decoration logic
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/healthchecks.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/cover/test_phases.py
Labels: docs, legibility

#2065 Fix for newest Lark parser
  hypothesis-python/RELEASE.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/src/hypothesis/extra/lark.py
  requirements/coverage.txt
Labels: meta, tests/build/CI

#2066 Created a better domain name strategy
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/vendor/tlds-alpha-by-domain.txt
  hypothesis-python/tests/cover/test_provisional_strategies.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: enhancement

#2076 Support `from_type` for abstract classes with unknown concrete subclasses
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: enhancement, interop
