Repository HypothesisWorks/hypothesis, pull requests merged in 2019-04, with the labels that each got.

#1912 Get our CI working again
  azure-pipelines.yml
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_verbosity.py
  hypothesis-python/tests/django/toys/settings.py
  hypothesis-python/tests/django/toystore/test_basic_configuration.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1904 Add special-case filtering for SampledFromStrategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/lazy.py
  hypothesis-python/src/hypothesis/searchstrategy/misc.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/tests/cover/test_sampled_from.py
  hypothesis-python/tests/nocover/test_sampled_from.py
Labels: enhancement

#1918 Correctly restore global RNG state after using random_module()
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_random_module.py
Labels: bug, tests/build/CI

#1894 Flatten .filter(...) chains into a single FilteredStrategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/tests/nocover/test_filtering.py
  hypothesis-python/tests/nocover/test_sampled_from.py
Labels: enhancement

#1922 Fix assertion failure in sampled_from(...).filter(...) when there are few elements and all are rejected
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/misc.py
  hypothesis-python/tests/cover/test_sampled_from.py
Labels: bug

#1920 Timedelta deadline
  .isort.cfg
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/tests/cover/test_settings.py
Labels: legibility

#1917 Support registered strategies for NewTypes in from_type (previously ignored)
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: enhancement

#1878 Adds numpy strategy: broadcastable shapes
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: new-feature

#1781 Multi-bug discovery during generation
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_flakiness.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/cover/test_testdecorators.py
Labels: enhancement

#1923 Run most tests under Windows on Pipelines
  azure-pipelines.yml
Labels: tests/build/CI

#1934 Check for shadowed tests with Pylint
  hypothesis-python/tests/common/debug.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/cover/test_simple_strings.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1933 Speed and stability improvements for our Numpy tests
  hypothesis-python/tests/cover/test_simple_collections.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: flaky-tests, tests/build/CI

#1921 Use new sampled_from implementation in stateful rule choice
  guides/strategies-that-shrink.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
Labels: legibility

#1877 A new strategy for generating functions
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/searchstrategy/functions.py
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_composite.py
  hypothesis-python/tests/cover/test_functions.py
  hypothesis-python/tests/cover/test_lambda_formatting.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/py3/test_functions.py
  hypothesis-python/tests/py3/test_lookup.py
  requirements/tools.txt
Labels: new-feature

#1891 Efficient unique collections with elements from a sampled_from
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/src/hypothesis/searchstrategy/misc.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/nocover/test_sampled_from.py
Labels: enhancement

#1945 Continue with unbiased generation while TargetSelector is empty
  guides/testing-hypothesis.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Labels: bug, flaky-tests
