Repository HypothesisWorks/hypothesis, pull requests merged in 2019-10, with the labels that each got.

#2006 Implement targeted PBT
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/__init__.py
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_targeting.py
Labels: new-feature

#2115 Test more new Pythons
  azure-pipelines.yml
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/py3/test_asyncio.py
  hypothesis-python/tests/pytest/test_capture.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2112 Fix #2106. Defer directory creation to DirectoryBasedExampleDatabase
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/configuration.py
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_filestorage.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/nocover/test_database_usage.py
Labels: enhancement, legibility

#2121 Add `Schemathesis` to the "Projects extending Hypothesis" list.
  hypothesis-python/docs/strategies.rst
Labels: docs

#2123 Numpy `basic_indexes(shape)` strategy
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: new-feature

#2120 Four tiny cleanups
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/searchstrategy/deferred.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
Labels: legibility

#2122 Implement `booleans()` and `just()` as `sampled_from()` for better collections
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/misc.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_simple_collections.py
Labels: performance

#2117 More precise strategy type-hints
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  whole-repo-tests/test_type_hints.py
Labels: legibility

#2134 Add `blacken-docs`
  hypothesis-python/README.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/django.rst
  hypothesis-python/docs/examples.rst
  hypothesis-python/docs/quickstart.rst
  hypothesis-python/docs/reproducing.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/tests/cover/test_statistical_events.py
  hypothesis-ruby/docs/design.md
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: docs, tests/build/CI

#2127 Allow `optional` fields in `fixed_dictionaries()`
  .isort.cfg
  guides/api-style.rst
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_simple_collections.py
  hypothesis-python/tests/numpy/test_argument_validation.py
Labels: new-feature

#2141 Better stats reporting for state machines
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_statistical_events.py
Labels: legibility

#2143 Remove one final use of md5
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/numpy/test_gen_data.py
  whole-repo-tests/test_security.py
Labels: enhancement, interop

#2147 Check for PRNG state leaks
  hypothesis-python/tests/conftest.py
Labels: tests/build/CI

#2152 Add photos of stickers and contributor pin
  brand/README.rst
  brand/pin.jpg
  brand/stickers.jpg
Labels: meta

#2137 Clean up core test case generation logic
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/common/debug.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_statistical_events.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/cover/test_verbosity.py
  hypothesis-python/tests/datetime/test_pytz_timezones.py
  hypothesis-python/tests/nocover/test_flatmap.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/pytest/test_statistics.py
  hypothesis-python/tests/quality/test_discovery_ability.py
Labels: enhancement

#2158 Add support for `SupportsIndex` in Python 3.8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: new-feature

#2156 Fix some flaky tests and fix a longstanding bug in recursive
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/recursive.py
  hypothesis-python/tests/cover/test_recursive.py
  hypothesis-python/tests/cover/test_reproduce_failure.py
  hypothesis-python/tests/quality/test_integers.py
Labels: bug, flaky-tests, tests/build/CI

#2157 Upgrade to the latest black
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/searchstrategy/attrs.py
  hypothesis-python/tests/common/__init__.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_conjecture_float_encoding.py
  hypothesis-python/tests/cover/test_phases.py
  hypothesis-python/tests/nocover/test_regressions.py
  hypothesis-python/tests/nocover/test_simple_numbers.py
  hypothesis-python/tests/quality/test_integers.py
  hypothesis-python/tests/quality/test_poisoned_lists.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
  hypothesis-python/tests/quality/test_zig_zagging.py
  requirements/tools.txt
Labels: tests/build/CI
