Repository HypothesisWorks/hypothesis, pull requests merged in 2019-12, with the labels that each got.

#2249 Explicitly check that @settings(parent) received a settings instance
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/tests/cover/test_settings.py
Labels: legibility

#2248 Fix UniqueSampledListStrategy bug
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/tests/cover/test_sampled_from.py
Labels: bug

#2245 Generate longer strings for unsized dtypes
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: bug

#2252 Hopefully make test_respects_max_examples_in_database_usage less flaky
  hypothesis-python/tests/nocover/test_database_usage.py
Labels: flaky-tests

#2254 Suppress flaky health check in test_still_tears_down_on_failed_assume
  hypothesis-python/tests/cover/test_setup_teardown.py
Labels: flaky-tests

#2260 Suppress flaky health check in test_mixing_is_sometimes_distorted
  hypothesis-python/tests/quality/test_discovery_ability.py
Labels: flaky-tests

#2244 Internal refactoring for ConjectureData
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/quality/test_poisoned_lists.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
Labels: internals

#2259 Improve draw with one of and empty bundle
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/misc.py
  hypothesis-python/src/hypothesis/searchstrategy/strategies.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_statistical_events.py
Labels: performance

#2253 Start testing in CI with Django 3.0; drop Django 2.0 testing
  azure-pipelines.yml
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2256 Warn when other decorators are used without `@given`
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/cover/test_reproduce_failure.py
  hypothesis-python/tests/pytest/test_checks.py
Labels: legibility

#2255 Update docs on optional dependencies
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/packaging.rst
  tooling/scripts/install-python.sh
Labels: docs

#2263 Remove max_chance and zero_chance from GenerationParameters
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
Labels: internals

#2243 Include highest `target` scores of failing tests in statistics
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/cover/test_statistical_events.py
Labels: enhancement

#2262 By default always run the maximum number of stateful test steps
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: internals

#2274 Hashable from type bug
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: bug

#2266 Add dedicated phase for targeted testing
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_targeting.py
Labels: internals

#2276 Add exact sticker image with "Hypothesis"
  brand/README.rst
  brand/sticker.png
Labels: meta

#2280 Fix flaky test in test_testdecorators.py
  hypothesis-python/tests/cover/test_testdecorators.py
Labels: flaky-tests

#2278 Enforce 100% coverage of conjecture with its own tests
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/tests/conjecture/__init__.py
  hypothesis-python/tests/conjecture/common.py
  hypothesis-python/tests/conjecture/test_choice_tree.py
  hypothesis-python/tests/conjecture/test_data_tree.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/conjecture/test_float_encoding.py
  hypothesis-python/tests/conjecture/test_intlist.py
  hypothesis-python/tests/conjecture/test_junkdrawer.py
  hypothesis-python/tests/conjecture/test_minimizer.py
  hypothesis-python/tests/conjecture/test_optimiser.py
  hypothesis-python/tests/conjecture/test_order_shrinking.py
  hypothesis-python/tests/conjecture/test_shrinker.py
  hypothesis-python/tests/conjecture/test_shrinking_interface.py
  hypothesis-python/tests/conjecture/test_test_data.py
  hypothesis-python/tests/conjecture/test_utils.py
  hypothesis-python/tests/cover/test_conjecture_utils.py
  hypothesis-python/tests/nocover/test_conjecture_engine.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2279 Improve optimiser algorithm
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/tests/conjecture/test_optimiser.py
  hypothesis-python/tests/conjecture/test_test_data.py
Labels: enhancement

#2281 Remove rust tests from travis
  .travis.yml
Labels: tests/build/CI

#2270 Track the pareto front in the example database
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/index.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/conjecture/test_pareto.py
  hypothesis-python/tests/cover/test_phases.py
  hypothesis-python/tests/py3/test_lookup.py
  hypothesis-python/tests/pytest/test_parametrized_db_keys.py
  requirements/test.in
  requirements/test.txt
  requirements/tools.in
  requirements/tools.txt
  tooling/setup.py
Labels: internals

#2269 Fix from_type bytestring/sequence issues
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: bug

#2283 Add notion of "tagging" to test cases and use it in pareto front calculations
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/tests/conjecture/test_pareto.py
  hypothesis-python/tests/conjecture/test_test_data.py
Labels: internals

#2261 Improve ability to generate duplicated values
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/tests/conjecture/test_test_data.py
  hypothesis-python/tests/cover/test_feature_flags.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/quality/test_discovery_ability.py
  hypothesis-python/tests/quality/test_shrink_quality.py
Labels: internals

#2284 Optimise the pareto front
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/conjecture/test_pareto.py
Labels: internals

#2285 Add new PyPI classifiers
  hypothesis-python/setup.py
  hypothesis-python/tests/py3/test_lookup.py
  mypy.ini
Labels: legibility

#2289 More improvements to optimiser algorithm
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/tests/conjecture/test_optimiser.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/nocover/test_targeting.py
Labels: internals

#2297 Better from type supports op
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/py3/test_lookup.py
  hypothesis-python/tox.ini
Labels: enhancement

#2298 Tiny cleanups before 5.0.x
  guides/testing-hypothesis.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/docs/django.rst
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/nocover/test_regex.py
Labels: tests/build/CI

#2282 Hypothesis 5.0: now with no deprecated behaviour... and no Python 2!
  .flake8
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/development.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/scripts/unicodechecker.py
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/__init__.py
  hypothesis-python/src/hypothesis/_error_if_old.py
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/README.rst
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/cover/test_detection.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_example.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/cover/test_phases.py
  hypothesis-python/tests/cover/test_reproduce_failure.py
  hypothesis-python/tests/cover/test_sampled_from.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/cover/test_simple_strings.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/cover/test_validation.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  hypothesis-python/tests/nocover/test_simple_numbers.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/py2/__init__.py
  hypothesis-python/tests/py2/test_destructuring.py
  hypothesis-python/tests/py2/test_generate_ints.py
  hypothesis-python/tests/py2/test_validation.py
  hypothesis-python/tests/pytest/test_capture.py
  hypothesis-python/tests/pytest/test_checks.py
  hypothesis-python/tox.ini
  requirements/py2.txt
  scripts/run_with_env.cmd
  tooling/src/hypothesistooling/__main__.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
Labels: meta
