Repository HypothesisWorks/hypothesis, pull requests merged in 2019-11, with the labels that each got.

#2162 Warn on settings without given at pytest_runtest_call
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/cover/test_debug_information.py
  hypothesis-python/tests/cover/test_settings.py
Labels: bug

#2159 Fix biased_coin doc
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/tests/pandas/test_indexes.py
Labels: legibility

#2168 Explain why launching "python -Werror" might mysteriously fail
  guides/testing-hypothesis.rst
  hypothesis-python/tests/cover/test_example.py
Labels: tests/build/CI

#2166 Fix loading of charmap from cache file
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/tests/cover/test_charmap.py
  hypothesis-python/tests/cover/test_deadline.py
Labels: bug

#2145 Make stateful assign to multiple variables when printing steps that return MultipleResults
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: bug, legibility

#2165 Only add profile info to pytest header if in verbose mode
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/cover/test_setup_teardown.py
  hypothesis-python/tests/pytest/test_profiles.py
Labels: enhancement

#2169 Improved handling of typevars
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: bug

#2173 New strategy: mutually broadcastable shapes
  .travis.yml
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/cover/test_statistical_events.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: new-feature

#2161 Add support for `typing.Literal` in Python 3.8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/py3/test_lookup.py
Labels: new-feature

#2171 Add `flake8-bugbear` to our CI
  .flake8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/searchstrategy/lazy.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/utils/dynamicvariables.py
  hypothesis-python/tests/cover/test_conjecture_utils.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/quality/test_shrink_quality.py
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/releasemanagement.py
Labels: tests/build/CI

#2179 Check that `strategy` argument to `data.draw()` is actually a strategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/tests/cover/test_direct_strategies.py
Labels: legibility

#2181 Update readthedocs config
  .readthedocs.yml
  .rtfd-reqs.txt
Labels: docs, tests/build/CI

#2183 Handle `floats()` width further down the stack
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/numbers.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_float_nastiness.py
Labels: performance

#2191 Declare Hypothesis for Ruby to be unsupported
  .travis.yml
  README.rst
  azure-pipelines.yml
  tooling/scripts/common.sh
  tooling/scripts/ensure-rustup.sh
  tooling/src/hypothesistooling/__init__.py
  tooling/src/hypothesistooling/__main__.py
  tooling/src/hypothesistooling/projects/hypothesisruby.py
  whole-repo-tests/test_version_sync.py
Labels: meta, tests/build/CI

#2185 Prune parts of the data tree that have discards in them
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_conjecture_data_tree.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/nocover/test_recursive.py
Labels: enhancement

#2184 Properly validate strategies used with test methods
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_core.py
Labels: bug, legibility

#2188 Skip the interactive test if -Werror fails
  hypothesis-python/tests/cover/test_example.py
Labels: tests/build/CI

#2197 Count `charmap()` towards `text()` drawtime
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/tests/cover/test_health_checks.py
Labels: bug, legibility

#2200 Upgrade `mutually_broadcastable_shapes()` to handle gufunc signatures
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gufunc.py
Labels: new-feature

#2198 Suport platforms where `__file__` is not defined
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/provisional.py
Labels: interop

#2205 Make @given raise "Missing required kwarg" errors lazily
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/py3/test_annotations.py
Labels: legibility

#2144 Write a JOSS paper for Hypothesis
  paper.bib
  paper.md
Labels: docs, meta

#2211 Clarify wording from JOSS paper review
  CODEOWNERS
  paper.md
Labels: meta

#2214 Improve wording of paper
  paper.md
Labels: meta

#2204 Avoid being the first to import large packages
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/entropy.py
  hypothesis-python/src/hypothesis/internal/floats.py
  hypothesis-python/tests/cover/test_lazy_import.py
  hypothesis-python/tests/nocover/test_skipping.py
  hypothesis-python/tests/numpy/test_lazy_import.py
Labels: interop

#2199 Describe and clarify some of the control flow in core.py
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Labels: meta

#2194 Disable pytest plugin if pytest is too old
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
Labels: interop

#2208 Support new-in-3.8 typing module types
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/types.py
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/cover/test_statistical_events.py
  hypothesis-python/tests/py3/test_async_def.py
  hypothesis-python/tests/py3/test_asyncio.py
  hypothesis-python/tests/py3/test_lookup.py
  hypothesis-python/tests/py3/test_lookup_py38.py
Labels: enhancement

#2213 Add argument validation for rule
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: legibility

#2206 Stop `floats(max_value=0.0, exclude_max=True)` generating `-0.0`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/tests/cover/test_float_nastiness.py
Labels: docs, legibility

#2189 Do not catch and record KeyboardInterrupt
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_baseexception.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: bug, legibility

#2216 Commonise logic between explicit examples and generation
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_explicit_examples.py
Labels: enhancement

#2228 Add missing word in README.rst
  README.rst
Labels: docs

#2232 Really deflake test this time
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: flaky-tests

#2202 Fix various typos in docstrings & comments
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/dpcontracts.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/floats.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/tests/django/toystore/forms.py
Labels: docs

#2234 Adjust flake8 config and drop pylint
  .flake8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/floats.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/cover/test_simple_collections.py
  hypothesis-python/tests/nocover/test_flatmap.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
  hypothesis-python/tests/quality/test_shrink_quality.py
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2207 Lots of small docs tweaks
  CITATION
  brand/README.rst
  brand/dragonfly-rainbow.png
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/docs/usage.rst
Labels: docs

#2235 Rebuild find on top of given
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/tests/common/debug.py
  hypothesis-python/tests/cover/test_find.py
  hypothesis-python/tests/cover/test_verbosity.py
Labels: internals

#2219 Bias initial data generation towards small test cases
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/src/hypothesis/internal/entropy.py
  hypothesis-python/tests/common/setup.py
  hypothesis-python/tests/cover/test_conjecture_junkdrawer.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/quality/test_discovery_ability.py
Labels: legibility, performance

#2238 Implement swarm testing and use it for rule based stateful tests
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/searchstrategy/featureflags.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_feature_flags.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_statistical_events.py
Labels: new-feature

#2237 Use `flake8-bandit` and `flake8-comprehensions`
  .flake8
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/dateutil.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/searchstrategy/datetime.py
  hypothesis-python/tests/cover/test_attrs_inference.py
  hypothesis-python/tests/cover/test_feature_flags.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/cover/test_simple_collections.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/nocover/test_from_type_recipe.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
  hypothesis-python/tests/nocover/test_strategy_state.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/py3/test_annotations.py
  hypothesis-python/tests/py3/test_lookup.py
  hypothesis-python/tests/quality/test_integers.py
  hypothesis-python/tests/quality/test_shrink_quality.py
  requirements/tools.in
  requirements/tools.txt
  tooling/scripts/tool-hash.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
  whole-repo-tests/test_security.py
Labels: tests/build/CI
