Repository HypothesisWorks/hypothesis, pull requests merged in 2019-05, with the labels that each got.

#1950 added range/xrange to from_type
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
Labels: enhancement, good first issue

#1952 Improve numpy array shapes
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement, good first issue

#1953 Fix 'duplicate link target' error
  hypothesis-python/docs/changes.rst
Labels: tests/build/CI

#1951 support slice in from_type
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/src/hypothesis/searchstrategy/types.py
Labels: enhancement, good first issue

#1947 Minor tweaks to contributor/maintainer guides
  guides/README.rst
  guides/internals.rst
  guides/review.rst
  hypothesis-python/docs/changes.rst
Labels: docs

#1962 Add feature for multiple unique_by functions
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_simple_collections.py
Labels: enhancement

#1963 Work around weird behavior of np.dtype
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
Labels: flaky-tests

#1954 Expose DataObject for type hints
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/strategies.py
  whole-repo-tests/test_type_hints.py
Labels: legibility, meta

#1960 Attempting to add #1929 (slices strategy)
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/strategies.py
  hypothesis-python/tests/cover/test_deadline.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_slices.py
Labels: new-feature

#1971 Add autoflake fixer
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/cache.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinking/common.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_unittest.py
  hypothesis-python/tests/nocover/test_modify_inner_test.py
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1967 Add "everything but" recipe using from_type
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/tests/nocover/test_from_type_recipe.py
Labels: docs

#1985 Consistently use dict/set literals and comprehensions
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/django/models.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/searchstrategy/collections.py
  hypothesis-python/src/hypothesis/searchstrategy/regex.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
  hypothesis-python/tests/cover/test_example.py
  hypothesis-python/tests/cover/test_explicit_examples.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/cover/test_regressions.py
  hypothesis-python/tests/nocover/test_collective_minimization.py
  hypothesis-python/tests/nocover/test_flatmap.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/quality/test_shrink_quality.py
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1990 Clarify error message for signature mismatch
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/nocover/test_testdecorators.py
Labels: legibility

#1995 Widen caught exception in rare database collision
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/internal/compat.py
Labels: bug

#1989 Deprecate GenericStateMachine
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_runner_strategy.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/pytest/test_statistics.py
Labels: legibility
