Repository HypothesisWorks/hypothesis, pull requests merged in 2019-03, with the labels that each got.

#1851 Small performance patch for Numpy arrays
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
Labels: performance

#1849 Speed up checks for structural changes in the shrink target
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/cover/test_conjecture_intlist.py
Labels: performance, test-case-reduction

#1848 Tighten validation of several settings
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/tests/cover/test_conjecture_utils.py
  hypothesis-python/tests/cover/test_explicit_examples.py
  hypothesis-python/tests/cover/test_flakiness.py
  hypothesis-python/tests/cover/test_settings.py
Labels: legibility

#1854 Port Travis testing config to Azure Pipelines
  CONTRIBUTING.rst
  azure-pipelines.yml
Labels: tests/build/CI

#1856 Remove a large number of jobs from Travis
  .travis.yml
Labels: tests/build/CI

#1852 Add strategy for generating values for the numpy-axis argument
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: new-feature

#1846 New Patricia trie based example cache
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/tests/cover/test_conjecture_data_tree.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_conjecture_float_encoding.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/nocover/test_conjecture_engine.py
  hypothesis-python/tests/nocover/test_conjecture_int_list.py
  hypothesis-python/tests/quality/test_integers.py
  hypothesis-python/tests/quality/test_poisoned_lists.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
  hypothesis-python/tests/quality/test_zig_zagging.py
  mypy.ini
Labels: enhancement, performance

#1861 Deprecate sampled_from([])
  guides/api-style.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/tests/cover/test_nothing.py
  hypothesis-python/tests/cover/test_reusable_values.py
  hypothesis-python/tests/cover/test_sampled_from.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: legibility

#1858 Move Windows, OSX builds to Pipelines
  azure-pipelines.yml
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#1866 Don't bother calculating the giant table of masks that we never use
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
Labels: performance

#1869 Don't rewrite novel buffers
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
Labels: performance

#1867 Remove lingering Block allocation
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
Labels: performance

#1868 Don't use a fresh context manager on every debug call
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/reporting.py
Labels: performance

#1790 Add guide to designing strategies for good shrinking behaviour.
  guides/strategies-that-shrink.rst
Labels: docs, opinions-sought

#1875 Improve memory usage and speed of long-running shrinks
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Labels: performance, test-case-reduction

#1873 Obtain the last block's length without having to create it
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
Labels: performance

#1874 Add setting to disable multi-bug reporting
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/cover/test_slippage.py
Labels: enhancement

#1865 Build example objects lazily
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/junkdrawer.py
  hypothesis-python/tests/cover/test_conjecture_engine.py
  hypothesis-python/tests/cover/test_conjecture_intlist.py
  hypothesis-python/tests/cover/test_conjecture_test_data.py
Labels: performance

#1860 Error on excluded infinite endpoints
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_strategies.py
  hypothesis-python/src/hypothesis/internal/floats.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
Labels: bug

#1883 Drop support for Python 3.4
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/searchstrategy/regex.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tox.ini
  scripts/install.ps1
  tooling/scripts/install-python.sh
  tooling/src/hypothesistooling/__main__.py
Labels: meta

#1886 Flaky test fixes
  hypothesis-python/tests/cover/test_complex_numbers.py
  hypothesis-python/tests/nocover/test_strategy_state.py
Labels: flaky-tests

#1888 Add hypothesis-networkx to strategies.rst
  hypothesis-python/docs/strategies.rst
Labels: docs

#1889 Add "mock" to the virtualenv setup instructions
  guides/testing-hypothesis.rst
Labels: docs, tests/build/CI

#1893 Fix flaky test_reusable_strategies_are_all_reusable
  hypothesis-python/tests/cover/test_reusable_values.py
Labels: flaky-tests

#1906 Derandomize test_can_disable_multiple_error_reporting to hopefully make it non-flaky
  hypothesis-python/tests/cover/test_slippage.py
Labels: flaky-tests

#1905 Improve error message if flatmap function doesn't return a strategy
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/searchstrategy/flatmapped.py
  hypothesis-python/tests/cover/test_searchstrategy.py
Labels: good first issue, legibility
