Repository HypothesisWorks/hypothesis, pull requests merged in 2020-02, with the labels that each got.

#2335 Improve repr of `from_type(...)` strategies
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_one_of.py
Labels: legibility

#2317 Migrate to keyword-only arguments
  .flake8
  guides/api-style.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_functions.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_numerics.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/cover/test_runner_strategy.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/nocover/test_argument_validation.py
  hypothesis-python/tests/numpy/test_fill_values.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement, legibility

#2343 Misc little cleanups
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
Labels: docs, internals

#2353 Don't recreate example groups for mutation, except when necessary
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Labels: performance

#2345 Patch `builds()` signature on py38 for pos-only `target` in docs
  .readthedocs.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
Labels: docs, legibility

#2355 Python 3.8 not yet available on readthedocs
  .readthedocs.yml
Labels: docs, tests/build/CI

#2354 Handle `datetime64`, `timedelta64` dtypes without time units
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: bug, legibility

#2358 Python 3.8 is now available on readthedocs
  .readthedocs.yml
Labels: docs, tests/build/CI

#2332 Refactoring stateful testing: rule-based all the way down
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: internals

#2356 Warn on `@given` + function-scoped fixtures
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/cover/test_mock.py
  hypothesis-python/tests/pytest/test_fixtures.py
Labels: interop, legibility
