Repository HypothesisWorks/hypothesis, pull requests merged in 2020-08, with the labels that each got.

#2344 Ghostwriter: writes tests for you
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/docs/ghostwriter.rst
  hypothesis-python/docs/index.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/tests/ghostwriter/recorded/base64_magic.txt
  hypothesis-python/tests/ghostwriter/recorded/eval_equivalent.txt
  hypothesis-python/tests/ghostwriter/recorded/sorted_idempotent.txt
  hypothesis-python/tests/ghostwriter/recorded/sorted_self_equivalent.txt
  hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
Labels: new-feature

#2543 Adds origin handling
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: enhancement

#2548 Add ghostwriter functions for binary ops and Numpy (g)ufuncs
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/tests/ghostwriter/recorded/addition_op_magic.txt
  hypothesis-python/tests/ghostwriter/recorded/division_operator.txt
  hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt
  hypothesis-python/tests/ghostwriter/recorded/multiplication_operator.txt
  hypothesis-python/tests/ghostwriter/recorded/multiplication_operator_unittest.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
Labels: new-feature

#2556 Add "hypothesis" entry point
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/src/hypothesis/__init__.py
  hypothesis-python/src/hypothesis/entry_points.py
Labels: new-feature

#2560 Add a way to get the strategy used for an `@given`-wrapped test
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_fuzz_one_input.py
Labels: internals, interop

#2568 Document and type-annotate database code
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/database.rst
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/tests/cover/test_database_backend.py
  hypothesis-python/tests/nocover/test_database_agreement.py
  hypothesis-python/tests/nocover/test_strategy_state.py
Labels: docs, legibility

#2573 Changes how TypeVar is registered, refs #2572
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: enhancement
