Repository HypothesisWorks/hypothesis, pull requests merged in 2020-01, with the labels that each got.

#2304 Improve `from_type(datetime.tzinfo)`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: enhancement

#2309 Convert type-hint comments to true annotations
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/dateutil.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/extra/pytz.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/src/hypothesis/internal/entropy.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_attrs_inference.py
  hypothesis-python/tests/numpy/test_gen_data.py
  mypy.ini
  requirements/coverage.txt
  requirements/test.txt
  requirements/tools.txt
  requirements/typing.in
  requirements/typing.txt
Labels: enhancement

#2313 Fix is_hypothesis_file internal function
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/tests/cover/test_escalation.py
Labels: bug, interop

#2315 Minor cleanups to docs formatting, coverage pragmas, and release automation
  .readthedocs.yml
  guides/api-style.rst
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/regex.py
  hypothesis-python/src/hypothesis/utils/conventions.py
  hypothesis-python/tests/cover/test_escalation.py
  tooling/src/hypothesistooling/__main__.py
Labels: docs, tests/build/CI

#2322 Ensure generic set elems can be hashed
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: enhancement

#2307 Generate non-UTF-8 strings for Numpy unicode datatype
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement

#2329 Roll back 5.2.0 (numpy unicode fun) for now
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: bug, flaky-tests, interop

#2316 New core strategies for IP addresses
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_provisional_strategies.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: new-feature

#2328 Remove stray closing parenthesis (settings docs)
  hypothesis-python/docs/settings.rst
Labels: docs

#2330 Tiny internal refactorings
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  requirements/coverage.txt
  requirements/test.in
  requirements/test.txt
  requirements/tools.txt
Labels: internals

#2321 Block install on Python < 3.5.2
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/_error_if_old.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
Labels: meta

#2333 Test against Pandas 1.0
  azure-pipelines.yml
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI
