Repository HypothesisWorks/hypothesis, pull requests merged in 2020-05, with the labels that each got.

#2416 Avoid importing Django if not needed
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
Labels: interop, performance

#2420 Fix assume-example-parametrize interaction
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_explicit_examples.py
Labels: interop

#2421 Cap wall-time duration of shrink phase
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/conjecture/test_engine.py
Labels: legibility, performance

#2410 Test that we still shrink after hitting the example limit
  hypothesis-python/tests/conjecture/test_engine.py
Labels: tests/build/CI

#2419 Small `from_type()` performance upgrade
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
Labels: performance

#2422 Per-phase statistics reporting
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/cover/test_statistical_events.py
Labels: enhancement, legibility

#2428 Add support for Python 3.9's NamedTuple changes
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
Labels: internals, interop, tests/build/CI

#2429 Deprecate min_magnitude=None
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_complex_numbers.py
Labels: legibility

#2435 Implement thread-local strategy cache
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_cache_implementation.py
Labels: bug

#2441 Python 3.9: Treat missing __args__ on generic types as None
  CONTRIBUTING.rst
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: bug, interop
