Repository HypothesisWorks/hypothesis, pull requests merged in 2020-12, with the labels that each got.

#2672 Cache fewer inputs when fuzzing
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_fuzz_one_input.py
  hypothesis-python/tests/cover/test_settings.py
Labels: performance

#2694 Code Review Handbook: Missing "if"
  guides/review.rst
Labels: docs

#2686 Recognise en/de function pairs in the ghostwriter
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
Labels: enhancement

#2670 Expand API style guide
  guides/api-style.rst
Labels: docs

#2690 Improve signature of `settings()`, for tab-completion and type checking
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/tests/cover/test_settings.py
Labels: docs, legibility

#2677 Use Django field validators to infer more precise strategies
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/tests/django/toystore/forms.py
  hypothesis-python/tests/django/toystore/test_given_forms.py
Labels: performance

#2666 Naive datetimes are never imaginary
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/tests/cover/test_datetimes.py
  pytest.ini
Labels: bug

#2682 `st.timezones()` strategy using the stdlib `zoneinfo` module
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/datetime/test_zoneinfo_timezones.py
  hypothesis-python/tox.ini
Labels: new-feature

#2695 Recommend using `sampled_from()` when `builds(Enum)` raises an error
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_direct_strategies.py
Labels: legibility

#2691 Improve error when generating a dataframe from `rows` and `columns` with `fill=None`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/tests/pandas/test_argument_validation.py
Labels: legibility

#2697 Fix indexing bug with explicit `@example` and `verbosity=quiet`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_verbosity.py
Labels: bug

#2715 Doc fix: The database setting doesn't actually allow string values
  hypothesis-python/RELEASE.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/tests/cover/test_settings.py
Labels: docs

#2721 Add a "tasks" task to print the list of tasks supported by the build system
  CONTRIBUTING.rst
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI
