Repository HypothesisWorks/hypothesis, pull requests merged in 2020-04, with the labels that each got.

#2385 Stop testing against EOL Django 1.11
  azure-pipelines.yml
  hypothesis-python/setup.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: meta, tests/build/CI

#2383 Refactoring for date and time strategies
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/datetime/test_dateutil_timezones.py
  hypothesis-python/tests/datetime/test_pytz_timezones.py
Labels: enhancement, internals

#2390 Speed up calculation of example groups used by the mutator
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
Labels: performance

#2388 Inspect `__signature__` attribute of classes in `builds()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/nocover/test_build_signature.py
Labels: enhancement, interop

#2359 Changes to documentation files to make them friendlier
  README.rst
  hypothesis-python/README.rst
  hypothesis-python/docs/index.rst
Labels: docs

#2397 Stop pareto optimisation once interesting examples have been found
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/tests/conjecture/test_pareto.py
Labels: performance, test-case-reduction

#2387 Clarify `binary()` docstring, pytest warning
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/nocover/test_sampled_from.py
Labels: docs, legibility

#2393 Report targets with falsifying example(s)
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/tests/nocover/test_targeting.py
Labels: legibility

#2409 Improved `get_type_hints()` for classes with forward references
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/cover/test_lookup_py36.py
  hypothesis-python/tests/cover/test_lookup_py38.py
Labels: enhancement
