Repository HypothesisWorks/hypothesis, pull requests merged in 2020-10, with the labels that each got.

#2567 Fix callable entry points
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/examples/example_hypothesis_entrypoint/example_hypothesis_entrypoint.py
  hypothesis-python/examples/example_hypothesis_entrypoint/setup.py
  hypothesis-python/examples/example_hypothesis_entrypoint/test_entrypoint.py
  hypothesis-python/src/hypothesis/entry_points.py
  hypothesis-python/tox.ini
Labels: docs, interop

#2622 New `RedisExampleDatabase`, `MultiplexedDatabase`, and `ReadOnlyDatabase` for team workflows
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/docs/database.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/extra/redis.py
  hypothesis-python/tests/cover/test_database_backend.py
  hypothesis-python/tests/redis/__init__.py
  hypothesis-python/tests/redis/test_redis_exampledatabase.py
Labels: new-feature

#2640 remove instanceof type check for signature hints
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/nocover/test_build_signature.py
Labels: enhancement

#2646 Bugfix for `st.from_type(typing.Iterable[T])`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent.txt
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
  tooling/src/hypothesistooling/__main__.py
Labels: bug

#2634 Improve support for `@st.composite` with `@classmethod` or `@staticmethod`
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_composite.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: enhancement

#2649 None-aware signature override
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/cover/test_lookup.py
  requirements/tools.in
  requirements/tools.txt
Labels: bug

#2653 Support PEP 585 parametrized standard types
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/cover/test_lookup_py37.py
Labels: enhancement, tests/build/CI

#2655 Register remaining non-async generic types
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_lookup_py36.py
  hypothesis-python/tests/cover/test_lookup_py37.py
Labels: enhancement

#2652 Remove shrinking exemption for errors inside strategies
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/tests/cover/test_escalation.py
Labels: legibility
