Repository HypothesisWorks/hypothesis, pull requests merged in 2020-09, with the labels that each got.

#2554 Ghostwriter upgrade: equivalence heuristic and lots of edge cases
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/ghostwriter/recorded/addition_op_multimagic.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
  hypothesis-python/tests/ghostwriter/try-writing-for-installed.py
Labels: enhancement

#2580 Fix/use signature type hints
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/tests/nocover/test_build_signature.py
Labels: enhancement

#2586 ensure array from arrays() owns its memory
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement

#2596 Make all sections use consistent case style.
  hypothesis-python/docs/data.rst
  hypothesis-python/docs/database.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/development.rst
  hypothesis-python/docs/examples.rst
  hypothesis-python/docs/manifesto.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/docs/reproducing.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/docs/support.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/docs/usage.rst
Labels: docs

#2600 modified example test_sum_is_positive_pyconau20
  hypothesis-python/docs/details.rst
Labels: docs

#2615 Drop Python 3.5 at end of life
  azure-pipelines.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/_error_if_old.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/floats.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/strategies/_internal/random.py
  hypothesis-python/src/hypothesis/strategies/_internal/regex.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/conjecture/test_pareto.py
  hypothesis-python/tests/conjecture/test_shrinking_dfas.py
  hypothesis-python/tests/conjecture/test_test_data.py
  hypothesis-python/tests/conjecture/test_utils.py
  hypothesis-python/tests/cover/test_annotations.py
  hypothesis-python/tests/cover/test_cathetus.py
  hypothesis-python/tests/cover/test_datetimes.py
  hypothesis-python/tests/cover/test_escalation.py
  hypothesis-python/tests/cover/test_explicit_examples.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_regex.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/cover/test_type_lookup_forward_ref.py
  hypothesis-python/tests/nocover/test_from_type_recipe.py
  hypothesis-python/tests/nocover/test_simple_numbers.py
  hypothesis-python/tests/numpy/test_lazy_import.py
  hypothesis-python/tests/quality/test_discovery_ability.py
  hypothesis-python/tests/quality/test_normalization.py
  hypothesis-python/tests/typing_extensions/test_backported_types.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: interop, meta

#2620 use strings for struct formats
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/floats.py
Labels: interop, legibility

#2601 Reuse up to `max_examples` from database when `Phase.generate` is disabled
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/conjecture/test_pareto.py
Labels: internals

#2619 Customise `nps.from_dtype()` with keyword argument passthrough
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/numpy/test_argument_validation.py
  hypothesis-python/tests/numpy/test_from_dtype.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: enhancement

#2627 Improve error messages for misused APIs
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_explicit_examples.py
  hypothesis-python/tests/cover/test_one_of.py
Labels: legibility
