Repository HypothesisWorks/hypothesis, pull requests merged in 2021-04, with the labels that each got.

#2918 Fix missing type annotation for settings.__call__
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  whole-repo-tests/test_type_hints.py
Labels: bug, interop

#2916 Auto-configuration of default ghostwriter style - pytest if installed, else unittest
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
Labels: enhancement

#2915 Preserve iteration order in `st.fixed_dictionaries()` and `@given()` kwargs
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/tests/nocover/test_testdecorators.py
Labels: legibility

#2924 Improve error message for certain empty enums
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_sampled_from.py
Labels: legibility

#2922 Teach the Ghostwriter to look for more roundtrips
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/tests/ghostwriter/recorded/magic_base64_roundtrip.txt
  hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Labels: enhancement

#2926 Fix abstract type bug
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: bug, enhancement

#2933 Test against Django 3.2
  .github/workflows/main.yml
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: interop, tests/build/CI

#2932 New error message for `builds(Optional[x])` suggesting `from_type()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: legibility

#2931 Syntax-highlight ghostwritten code in the terminal using Rich
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/cli.py
Labels: enhancement

#2925 Improve exception handling in ghostwritten tests
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/ghostwriter/recorded/division_binop_error_handler.txt
  hypothesis-python/tests/ghostwriter/recorded/division_fuzz_error_handler.txt
  hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_arithmeticerror_handler.txt
  hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_error_handler.txt
  hypothesis-python/tests/ghostwriter/recorded/division_roundtrip_typeerror_handler.txt
  hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
  hypothesis-python/tests/ghostwriter/recorded/timsort_idempotent_asserts.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
Labels: enhancement

#2929 Teach the Ghostwriter to parse types from structured docstrings
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/docs/endorsements.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/docs/numpy.rst
  hypothesis-python/docs/packaging.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/docs/usage.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/ghostwriter/recorded/fuzz_with_docstring.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
Labels: enhancement

#2947 Use new importlib API
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/entry_points.py
Labels: interop
