Repository HypothesisWorks/hypothesis, pull requests merged in 2021-09, with the labels that each got.

#3084 Implement `return_value` healthcheck in stateful testing
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/src/hypothesis/strategies/_internal/attrs.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/cover/test_stateful.py
  requirements/tools.in
  requirements/tools.txt
Labels: legibility

#3087 Fix off-by-one error in `st.slices()`, and allow `step=None`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_slices.py
Labels: bug

#3088 Fix for inline `given()` on bound methods
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_reflection.py
Labels: bug

#3065 Array API extra
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/docs/numpy.rst
  hypothesis-python/src/hypothesis/extra/array_api.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/tests/array_api/__init__.py
  hypothesis-python/tests/array_api/common.py
  hypothesis-python/tests/array_api/conftest.py
  hypothesis-python/tests/array_api/test_argument_validation.py
  hypothesis-python/tests/array_api/test_arrays.py
  hypothesis-python/tests/array_api/test_from_dtype.py
  hypothesis-python/tests/array_api/test_indices.py
  hypothesis-python/tests/array_api/test_partial_adoptors.py
  hypothesis-python/tests/array_api/test_pretty.py
  hypothesis-python/tests/array_api/test_scalar_dtypes.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: new-feature, interop

#3095 Improved handling of required args via `inspect.signature()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/array_api.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/internal/healthcheck.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_annotations.py
  hypothesis-python/tests/cover/test_lambda_formatting.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_lookup_py38.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/cover/test_seed_printing.py
  hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
  hypothesis-python/tests/numpy/test_gufunc.py
  hypothesis-python/tests/pytest/test_capture.py
  tooling/setup.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
Labels: enhancement

#3097 Ghostwriter support for more builtins
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/ghostwriter/recorded/magic_builtins.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
Labels: enhancement

#3100 Fix given decorator type hint when decorating async functions
  AUTHORS.rst
  guides/documentation.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
Labels: legibility

#3107 Treat `SystemExit` and `GeneratorExit` as normal test failures
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/_array_helpers.py
  hypothesis-python/src/hypothesis/internal/conjecture/dfa/lstar.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/deferred.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/strategies/_internal/random.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/nocover/test_baseexception.py
  hypothesis-python/tests/quality/test_poisoned_lists.py
  hypothesis-python/tests/quality/test_poisoned_trees.py
  requirements/test.txt
  requirements/tools.txt
Labels: enhancement, interop
