Repository HypothesisWorks/hypothesis, pull requests merged in 2021-08, with the labels that each got.

#3047 Fix docs, and selftest compatibility with `pytest-randomly`
  hypothesis-python/docs/data.rst
  hypothesis-python/tests/conftest.py
Labels: docs, tests/build/CI

#2952 Improve `try_issubclass`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup_py37.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: bug

#3063 Adds a failing test for #3060
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/nocover/test_drypython_returns.py
Labels: bug, interop

#3056 Improve error message when `@given()` is applied to an `async def` function
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_given_error_conditions.py
  tooling/src/hypothesistooling/__main__.py
Labels: legibility

#3076 Faster strategy for `arrays(..., unique=True)`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: performance
