Repository HypothesisWorks/hypothesis, pull requests merged in 2021-01, with the labels that each got.

#2674 Move our all our CI to GitHub Actions
  .github/workflows/main.yml
  AUTHORS.rst
  build.sh
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2718 Fix test issue, add missing changelog line
  guides/api-style.rst
  guides/strategies-that-shrink.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/tests/cover/test_unittest.py
Labels: docs, tests/build/CI

#2728 Type-annotate rarely used public APIs
  azure-pipelines.yml
  build.sh
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/supported.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_example.py
Labels: legibility

#2688 Special-case `sampled_from(...).filter(...).map(...)` in unique collections
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/cover/test_fuzz_one_input.py
  hypothesis-python/tests/cover/test_sampled_from.py
Labels: performance

#2687 Make `dictionaries(keys=sampled_from(...), ...)` more efficient
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_sampled_from.py
Labels: performance

#2724 Resolve mutually-recursive `ForwardRef`
  .github/workflows/main.yml
  CONTRIBUTING.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/deferred.py
  hypothesis-python/tests/README.rst
  hypothesis-python/tests/conftest.py
  hypothesis-python/tests/nocover/test_type_lookup_forward_ref.py
  secrets.tar.enc
  tooling/src/hypothesistooling/__init__.py
  tooling/src/hypothesistooling/__main__.py
  tooling/src/hypothesistooling/projects/conjecturerust.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
  whole-repo-tests/test_secrets.py
Labels: bug

#2732 Support `Literal` on py36
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/typing_extensions/test_backported_types.py
Labels: enhancement

#2712 First codemods: fix positional arguments for keyword-only parameters
  guides/review.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/scripts/basic-test.sh
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/extra/cli.py
  hypothesis-python/src/hypothesis/extra/codemods.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/codemods/test_codemod_cli.py
  hypothesis-python/tests/codemods/test_codemods.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/nocover/test_regressions.py
  requirements/tools.in
  requirements/tools.txt
Labels: new-feature

#2726 Distinguish `from_type()` from `builds()` by inferring strategies for parameters with default values
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/nocover/test_build_signature.py
Labels: enhancement

#2741 Don't `pip install hypothesis-python/` in build.sh
  build.sh
Labels: tests/build/CI

#2723 Improve results from `hypothesis write hypothesis`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
  hypothesis-python/tests/ghostwriter/test_expected_output.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Labels: enhancement

#2736 Initial cache implementation
  .github/workflows/main.yml
Labels: performance, tests/build/CI

#2742 Add `currently_in_test_context()` to check if you can call `assume()`, `target()`, etc.
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/src/hypothesis/__init__.py
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/tests/cover/test_control.py
Labels: enhancement

#2738 Add HealthCheck.function_scoped_fixture to suppress fixture warnings
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/pytest/test_fixtures.py
Labels: legibility

#2680 Resurrect hypothesis-ruby by replacing the Rust / Ruby interop with Rutie
  .github/workflows/main.yml
  README.rst
  hypothesis-ruby/Cargo.toml
  hypothesis-ruby/Gemfile
  hypothesis-ruby/Gemfile.lock
  hypothesis-ruby/RELEASE.md
  hypothesis-ruby/Rakefile
  hypothesis-ruby/hypothesis-specs.gemspec
  hypothesis-ruby/lib/hypothesis.rb
  hypothesis-ruby/lib/hypothesis/engine.rb
  hypothesis-ruby/src/lib.rs
  tooling/src/hypothesistooling/__init__.py
  tooling/src/hypothesistooling/__main__.py
  tooling/src/hypothesistooling/projects/conjecturerust.py
  tooling/src/hypothesistooling/projects/hypothesisruby.py
Labels: Ruby

#2744 Hypothesis 6.0: starting 2021 as we mean to go on
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/codemods.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/internal/validation.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/tests/cover/test_complex_numbers.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_provisional_strategies.py
  hypothesis-python/tests/cover/test_randoms.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  hypothesis-python/tests/pytest/test_fixtures.py
Labels: legibility

#2750 Test PyPy 3.7 in CI
  .github/workflows/main.yml
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2753 Remove references to RSpec.
  hypothesis-ruby/Gemfile
  hypothesis-ruby/Gemfile.lock
  hypothesis-ruby/README.markdown
  hypothesis-ruby/RELEASE.md
  hypothesis-ruby/Rakefile
  hypothesis-ruby/docs/debt.md
  hypothesis-ruby/lib/hypothesis/engine.rb
  tooling/src/hypothesistooling/__main__.py
Labels: Ruby

#2754 Remove `Clone` trait impl from `Engine`
  conjecture-rust/src/engine.rs
  hypothesis-ruby/docs/debt.md
Labels: Rust

#2743 Refactor pytest plugin statistics handling for strict JUnit xml validation
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py
  hypothesis-python/tests/conjecture/test_dfa.py
  hypothesis-python/tests/pytest/test_statistics.py
Labels: enhancement, interop

#2761 Fix some clippy errors.
  conjecture-rust/src/data.rs
  conjecture-rust/src/database.rs
  conjecture-rust/src/distributions.rs
  conjecture-rust/src/engine.rs
Labels: Rust

#2768 Improve type annotations for `one_of` and `SearchStrategy.__or__`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/cover/test_searchstrategy.py
  whole-repo-tests/test_type_hints.py
Labels: legibility

#2772 Support skipping shrinking
  conjecture-rust/src/engine.rs
  hypothesis-ruby/RELEASE.md
  hypothesis-ruby/lib/hypothesis.rb
  hypothesis-ruby/lib/hypothesis/engine.rb
  hypothesis-ruby/spec/phase_specification_spec.rb
  hypothesis-ruby/spec/spec_helper.rb
  hypothesis-ruby/src/lib.rs
Labels: Ruby, Rust

#2775 Meta updates for conjecture rust
  conjecture-rust/Cargo.toml
  conjecture-rust/RELEASE.md
  conjecture-rust/src/database.rs
  conjecture-rust/src/distributions.rs
  conjecture-rust/src/engine.rs
  conjecture-rust/src/intminimize.rs
  conjecture-rust/src/lib.rs
  hypothesis-ruby/Cargo.toml
  hypothesis-ruby/RELEASE.md
  tooling/src/hypothesistooling/projects/conjecturerust.py
  tooling/src/hypothesistooling/projects/hypothesisruby.py
Labels: Rust

#2791 Update release guide and document our thread-safety policy
  .gitignore
  build.sh
  guides/documentation.rst
  guides/review.rst
  hypothesis-python/docs/conf.py
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/strategies.rst
  requirements/tools.in
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: docs

#2793 Distinguish exceptions by `__cause__` or `__context__`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/tests/nocover/test_interesting_origin.py
Labels: enhancement
