Repository HypothesisWorks/hypothesis, pull requests merged in 2021-06, with the labels that each got.

#2999 Enable coloured terminal output in CI logs via `PY_COLORS=1` 🌈
  .github/workflows/main.yml
  hypothesis-python/tox.ini
Labels: tests/build/CI

#2998 Fix existing tests that accidentally enable `Phase.explain`
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/conjecture/test_utils.py
  hypothesis-python/tests/cover/test_scrutineer.py
  hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
  hypothesis-python/tests/nocover/test_lstar.py
Labels: tests/build/CI

#3001 Remove various obsolete helper functions from `compat.py`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinking/dfas.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/reporting.py
  hypothesis-python/tests/cover/test_float_nastiness.py
  hypothesis-python/tests/cover/test_simple_strings.py
  hypothesis-python/tests/nocover/test_regex.py
  hypothesis-python/tests/nocover/test_strategy_state.py
  hypothesis-python/tests/numpy/test_from_dtype.py
  tooling/scripts/tool-hash.py
  tooling/src/hypothesistooling/__main__.py
Labels: internals

#3000 Produce a coverage report even if the test suite fails
  .github/workflows/main.yml
  hypothesis-python/tox.ini
Labels: tests/build/CI

#3003 Include xpassing tests in the pytest test summary
  pytest.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#3002 Run the main non-coverage tests with `-nauto` instead of `-n2`
  hypothesis-python/scripts/basic-test.sh
Labels: tests/build/CI

#3004 Remove `compat.py` and other files from the coverage blocklist
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/tests/cover/test_compat.py
  hypothesis-python/tests/nocover/test_compat.py
  hypothesis-python/tests/numpy/test_floor_ceil.py
Labels: internals, tests/build/CI

#3007 Produce more helpful output from `validate_branch_check.py`
  hypothesis-python/scripts/validate_branch_check.py
  whole-repo-tests/test_validate_branch_check.py
Labels: tests/build/CI

#3015 Improve explain-mode performance
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/scrutineer.py
  hypothesis-python/tests/cover/test_scrutineer.py
  hypothesis-python/tests/nocover/test_scrutineer.py
Labels: legibility, performance, tests/build/CI
