Repository HypothesisWorks/hypothesis, pull requests merged in 2021-03, with the labels that each got.

#2883 Check multiple preconditions
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: bug, enhancement

#2886 Fixes an exception in from_type(Union[Literal["a"], Literal["b"]]).example() in Python 3.6
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/typing_extensions/test_backported_types.py
Labels: bug

#2885 Adds no-implicit-reexport mypy option and refactors all violations
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/database.py
  hypothesis-python/src/hypothesis/extra/dateutil.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/extra/pytz.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/datatree.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/src/hypothesis/internal/entropy.py
  hypothesis-python/src/hypothesis/internal/escalation.py
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/random.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  mypy.ini
Labels: interop, legibility, tests/build/CI

#2889 Improve handling of self-referential `recursive()` strategies
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/recursive.py
  hypothesis-python/tests/nocover/test_recursive.py
Labels: bug, internals

#2859 Scrutineer: integrating opportunistic fault-localisation with PBT
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/internal/scrutineer.py
  hypothesis-python/tests/cover/test_phases.py
  hypothesis-python/tests/cover/test_scrutineer.py
Labels: new-feature

#2882 Allow `@rule()` xor `@invariant()` decorators on rule-based state machine methods.
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: legibility

#2892 Improve error message for `from_type(Type["int"])`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_type_lookup_forward_ref.py
Labels: legibility

#2887 Default to checking stateful invariants only after initialization
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: enhancement

#2895 De-flake test
  hypothesis-python/tests/nocover/test_interesting_origin.py
Labels: flaky-tests

#2900 Support testing with plugins
  hypothesis-python/tests/common/setup.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: interop, tests/build/CI

#2899 Handle all builtin types in `st.from_type()`, including via `Type[...]` and `ForwardRef(...)`
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/cover/test_lookup.py
Labels: enhancement

#2878 Upgrade `integers()` backend and filter rewriting
  CODEOWNERS
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/src/hypothesis/strategies/_internal/ipaddress.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/conjecture/test_engine.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_filter_rewriting.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/quality/test_discovery_ability.py
  hypothesis-python/tests/quality/test_integers.py
  requirements/coverage.txt
  requirements/tools.txt
Labels: enhancement

#2893 Typos fixed
  conjecture-rust/CHANGELOG.md
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/conjecture/dfa/__init__.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/statistics.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/cover/test_type_lookup_forward_ref.py
  hypothesis-python/tests/lark/test_grammar.py
  hypothesis-python/tests/nocover/test_regex.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-ruby/CHANGELOG.md
  hypothesis-ruby/RELEASE.md
  hypothesis-ruby/lib/hypothesis.rb
  requirements/tools.in
  requirements/tools.txt
  tooling/ignore-list.txt
  tooling/src/hypothesistooling/__main__.py
Labels: docs, legibility

#2910 Tiny ghostwriter fixes
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/tests/ghostwriter/recorded/magic_gufunc.txt
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
Labels: enhancement
