Repository HypothesisWorks/hypothesis, pull requests merged in 2021-02, with the labels that each got.

#2857 Removes skip check from CI
  .github/workflows/main.yml
Labels: tests/build/CI

#2854 Report statistics summary via `pytest-html`
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/extras.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  pytest.ini
  tooling/src/hypothesistooling/__main__.py
Labels: interop, legibility

#2865 Bump required pytest version to 4.6
  .github/workflows/main.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/pytestplugin.py
  hypothesis-python/tests/pytest/test_skipping.py
  hypothesis-python/tests/pytest/test_statistics.py
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#2864 Resolve pytest warnings about the deprecated --strict flag
  hypothesis-python/tests/pytest/test_mark.py
  hypothesis-python/tests/pytest/test_seeding.py
  hypothesis-python/tests/pytest/test_skipping.py
  hypothesis-python/tox.ini
  pytest.ini
Labels: tests/build/CI

#2853 Rewrite simple filters for bounded `integers()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/cover/test_filter_rewriting.py
  hypothesis-python/tests/cover/test_filtered_strategy.py
Labels: enhancement, performance

#2874 FIX #2872: allow to register default strategies for typed-dict based classes
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/cover/test_lookup_py38.py
Labels: bug, enhancement

#2877 Refactoring: move strategies out of `core.py`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/strategies/_internal/regex.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/utils.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/nocover/test_argument_validation.py
Labels: internals

#2867 Tidying up stateful testing
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/stateful.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
  requirements/coverage.txt
  requirements/tools.txt
Labels: docs, internals
