Repository HypothesisWorks/hypothesis, pull requests merged in 2021-05, with the labels that each got.

#2956 Allow `target()` inline in expressions
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/tests/nocover/test_targeting.py
Labels: enhancement

#2949 AST-based filter rewriting for lambdas
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/tests/cover/test_filter_rewriting.py
  hypothesis-python/tests/cover/test_filtered_strategy.py
Labels: enhancement, legibility, performance

#2965 Ensure `filter` appears in repr of `just(...).filter(...)`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/tests/nocover/test_pretty_repr.py
Labels: legibility

#2969 Register all core strategy functions through `@defines_strategy`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/__init__.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/utils.py
  hypothesis-python/tests/cover/test_type_lookup.py
Labels: internals

#2972 `sampled_from` and `just` should not have reusable values if transformed
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/strategies/_internal/utils.py
  hypothesis-python/tests/cover/test_reusable_values.py
  hypothesis-python/tests/nocover/test_reusable_values.py
Labels: bug

#2970 add .hypothesis to invalid tests
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_fuzz_one_input.py
  hypothesis-python/tests/nocover/test_modify_inner_test.py
Labels: bug, interop

#2968 Quiet identity element search in binary-operation ghostwriter
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
Labels: bug, legibility

#2973 Replace our own `raises` test helper with `pytest.raises`
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_arbitrary_data.py
  hypothesis-python/tests/cover/test_explicit_examples.py
  hypothesis-python/tests/cover/test_reflection.py
  hypothesis-python/tests/cover/test_simple_strings.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_testdecorators.py
  hypothesis-python/tests/nocover/test_floating.py
  hypothesis-python/tests/nocover/test_testdecorators.py
  hypothesis-python/tests/quality/test_discovery_ability.py
Labels: tests/build/CI

#2974 Move some slow tests into `nocover/`
  hypothesis-python/tests/conjecture/test_lstar.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/cover/test_targeting.py
  hypothesis-python/tests/nocover/test_lstar.py
  hypothesis-python/tests/nocover/test_stateful.py
  hypothesis-python/tests/nocover/test_targeting.py
Labels: tests/build/CI

#2980 Bounded `integers` should shrink towards positive values
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/tests/cover/test_testdecorators.py
  hypothesis-python/tests/nocover/test_integer_ranges.py
  hypothesis-python/tests/quality/test_shrink_quality.py
Labels: bug

#2983 `from_regex("", fullmatch=True)` should only produce empty strings
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/regex.py
  hypothesis-python/tests/cover/test_regex.py
Labels: bug

#2984 Avoid/ignore unhelpful numpy warnings in `test_can_minimize_float_arrays`
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: tests/build/CI

#2981 Speed up some slow `nocover/` tests
  hypothesis-python/tests/nocover/test_database_usage.py
  hypothesis-python/tests/nocover/test_imports.py
  hypothesis-python/tests/nocover/test_lstar.py
  hypothesis-python/tests/nocover/test_type_lookup_forward_ref.py
Labels: tests/build/CI

#2986 Use a single `Sampler` instance for all wide-range integer draws
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
Labels: performance

#2988 Simplify the `do_filtered_draw` hook
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/misc.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/cover/test_sampled_from.py
  hypothesis-python/tests/cover/test_searchstrategy.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: internals

#2994 Exclude `tests/quality/` from Windows CI builds
  .github/workflows/main.yml
Labels: tests/build/CI

#2992 Enable CI caching on MacOS
  .github/workflows/main.yml
Labels: tests/build/CI

#2995 Fix flaky coverage of fragments in the `urls` strategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_provisional_strategies.py
  requirements/test.txt
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
  whole-repo-tests/test_rst_is_valid.py
Labels: flaky-tests, tests/build/CI

#2996 Make example-discovery tests give up early if they can't hit their target
  hypothesis-python/tests/quality/test_discovery_ability.py
Labels: tests/build/CI
