Repository HypothesisWorks/hypothesis, pull requests merged in 2022-06, with the labels that each got.

#3376 Fix pipenv install issue and sometimes-too-short draw time healthcheck
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_control.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/nocover/test_interesting_origin.py
  hypothesis-python/tests/nocover/test_targeting.py
Labels: enhancement, interop

#3382 Fix `InferType` and improve type-checker tests
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  requirements/tools.txt
  whole-repo-tests/test_mypy.py
  whole-repo-tests/test_pyright.py
Labels: tests/build/CI, legibility

#3386 Avoid silently skipped tests
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/cover/test_core.py
  hypothesis-python/tests/cover/test_fuzz_one_input.py
Labels: legibility

#3385 Filter-rewriting for `st.floats()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/filtering.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/tests/cover/test_filter_rewriting.py
Labels: enhancement, performance
