Repository HypothesisWorks/hypothesis, pull requests merged in 2022-04, with the labels that each got.

#3278 Fix `given(...)(lambda x: ...)()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_testdecorators.py
Labels: bug

#3247 Make `hypothesis.infer` an alias for `...` and enable `@given(...)` to infer-all
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/details.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/errors.py
  hypothesis-python/src/hypothesis/extra/django/_fields.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/ghostwriter.py
  hypothesis-python/src/hypothesis/strategies/_internal/attrs.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/src/hypothesis/utils/conventions.py
  hypothesis-python/tests/cover/test_attrs_inference.py
  hypothesis-python/tests/cover/test_functions.py
  hypothesis-python/tests/cover/test_given_error_conditions.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_lookup_py37.py
  hypothesis-python/tests/cover/test_type_lookup.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  mypy.ini
Labels: new-feature

#3284 Quieter and prettier `functions()` strategy
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/functions.py
  hypothesis-python/src/hypothesis/strategies/_internal/lazy.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/cover/test_functions.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/cover/test_reflection.py
Labels: enhancement

#3290 Explicit error if `@pytest.fixture()` is applied after `@given()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/_hypothesis_pytestplugin.py
  hypothesis-python/tests/pytest/test_fixtures.py
Labels: legibility, interop

#3291 Error out on unhandlable psudeo-generics from Pydantic
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
Labels: legibility, interop

#3307 Add pypy39 to CI; add tests so we notice new releases in future
  .github/workflows/main.yml
  build.sh
  hypothesis-python/tox.ini
  tooling/src/hypothesistooling/__main__.py
  whole-repo-tests/test_ci_config.py
Labels: tests/build/CI
