Repository HypothesisWorks/hypothesis, pull requests merged in 2023-01, with the labels that each got.

#3538 Stop generating R-LDH labels in domains and emails
  .github/workflows/main.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/_error_if_old.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/django/_impl.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/internal/entropy.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/random.py
  hypothesis-python/src/hypothesis/strategies/_internal/types.py
  hypothesis-python/src/hypothesis/vendor/tlds-alpha-by-domain.txt
  hypothesis-python/tests/cover/test_randoms.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tests/pytest/test_capture.py
  hypothesis-python/tox.ini
  requirements/coverage.txt
  requirements/test.txt
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: bug

#3539 Refactor pretty-printer to unlock future upgrades
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/cover/test_falsifying_example_output.py
  hypothesis-python/tests/cover/test_pretty.py
Labels: internals

#3536 `get_type_hints()` support for `partial()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_compat.py
Labels: enhancement

#3537 New method: `@example(...).xfail()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/reproducing.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_example.py
  hypothesis-python/tests/nocover/test_integer_ranges.py
Labels: new-feature

#3540 Represent objects by the call that made them
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/data.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/scrutineer.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/cover/test_custom_reprs.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/quality/test_discovery_ability.py
  hypothesis-python/tests/quality/test_normalization.py
Labels: new-feature

#3561 Define a pretty printer for enums
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/cover/test_pretty.py
Labels: enhancement
