Repository HypothesisWorks/hypothesis, pull requests merged in 2023-04, with the labels that each got.

#3616 Separable parts of Inquisitor
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/tests/cover/test_database_backend.py
  requirements/coverage.txt
  requirements/test.txt
  requirements/tools.txt
Labels: internals

#3621 Internal refactorings
  AUTHORS.rst
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/provisional.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/array_api/test_arrays.py
  hypothesis-python/tests/common/debug.py
  hypothesis-python/tests/common/utils.py
  hypothesis-python/tests/cover/test_pretty.py
  hypothesis-python/tests/cover/test_randoms.py
  hypothesis-python/tests/django/toys/settings.py
  hypothesis-python/tests/django/toystore/test_given_models.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter.py
  hypothesis-python/tests/nocover/test_regex.py
  requirements/coverage.txt
  requirements/tools.txt
Labels: internals

#3619 fix: enables default encoding warning to ensure users set encoding
  hypothesis-python/tests/codemods/test_codemod_cli.py
  hypothesis-python/tests/cover/test_lazy_import.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/ghostwriter/test_ghostwriter_cli.py
  hypothesis-python/tests/ghostwriter/try-writing-for-installed.py
  hypothesis-python/tests/pytest/test_pytest_detection.py
  hypothesis-python/tox.ini
Labels: interop, internals

#3555 "Inquisitor": annotate parts of a minimal failing example which may vary
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/src/hypothesis/control.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/conjecture/test_inquisitor.py
  hypothesis-python/tests/cover/test_random_module.py
  hypothesis-python/tests/cover/test_slippage.py
  hypothesis-python/tests/nocover/test_collective_minimization.py
  hypothesis-python/tox.ini
Labels: new-feature, legibility, internals

#3626 Fix old Numpy compatibility
  .github/workflows/main.yml
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/tests/conjecture/test_float_encoding.py
  hypothesis-python/tests/cover/test_stateful.py
  hypothesis-python/tests/numpy/test_gen_data.py
  hypothesis-python/tox.ini
  tooling/scripts/common.sh
  tooling/src/hypothesistooling/__main__.py
  tooling/src/hypothesistooling/installers.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
  tooling/src/hypothesistooling/scripts.py
Labels: bug, tests/build/CI

#3628 Improved error messages for incompatible datetime & timedelta dtypes
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/src/hypothesis/extra/pandas/impl.py
  hypothesis-python/src/hypothesis/version.py
  hypothesis-python/tests/pandas/test_argument_validation.py
  tooling/src/hypothesistooling/projects/hypothesispython.py
Labels: legibility

#3631 Write `.patch` files to add `@example()` decorators for failing test cases
  hypothesis-python/.coveragerc
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/changes.rst
  hypothesis-python/docs/settings.rst
  hypothesis-python/scripts/other-tests.sh
  hypothesis-python/src/_hypothesis_pytestplugin.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/_patching.py
  hypothesis-python/src/hypothesis/extra/codemods.py
  hypothesis-python/src/hypothesis/internal/charmap.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
  hypothesis-python/src/hypothesis/strategies/_internal/numbers.py
  hypothesis-python/src/hypothesis/vendor/pretty.py
  hypothesis-python/tests/conjecture/test_inquisitor.py
  hypothesis-python/tests/patching/__init__.py
  hypothesis-python/tests/patching/callables.py
  hypothesis-python/tests/patching/test_patching.py
  hypothesis-python/tox.ini
  requirements/coverage.txt
  requirements/tools.txt
Labels: new-feature
