Repository HypothesisWorks/hypothesis, pull requests merged in 2024-03, with the labels that each got.

#3905 Fix 32-bit architecture detection in pandas index test
  hypothesis-python/tests/pandas/test_indexes.py
Labels: tests/build/CI

#3910 Fix missing-`fill` problem in `arrays()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/strategies/_internal/collections.py
  hypothesis-python/tests/numpy/test_gen_data.py
Labels: performance

#3806 WIP: support for `crosshair` backend
  hypothesis-python/RELEASE.rst
  hypothesis-python/docs/strategies.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/_settings.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/utils.py
  hypothesis-python/src/hypothesis/strategies/_internal/strategies.py
  hypothesis-python/tests/conjecture/test_alt_backend.py
  hypothesis-python/tests/cover/test_health_checks.py
  hypothesis-python/tests/cover/test_settings.py
  hypothesis-python/tests/ghostwriter/recorded/hypothesis_module_magic.txt
Labels: new-feature, interop, internals

#3920 Fix performance of `RuleBasedStateMachine` with data-hungry rules
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/tests/cover/test_stateful.py
Labels: performance

#3934 Work around weird lambda issue by popping entry from `linecache`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/reflection.py
  hypothesis-python/tests/cover/test_filter_rewriting.py
  hypothesis-python/tests/cover/test_lambda_formatting.py
Labels: tests/build/CI

#3935 Parallel coverage tests
  .github/workflows/main.yml
  .gitignore
  build.sh
  hypothesis-python/RELEASE.rst
  hypothesis-python/scripts/validate_branch_check.py
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/extra/_patching.py
  hypothesis-python/src/hypothesis/extra/array_api.py
  hypothesis-python/src/hypothesis/internal/conjecture/data.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/coverage.py
  hypothesis-python/src/hypothesis/internal/observability.py
  hypothesis-python/src/hypothesis/stateful.py
  hypothesis-python/src/hypothesis/strategies/_internal/datetime.py
  hypothesis-python/tests/common/setup.py
  hypothesis-python/tox.ini
  pytest.ini
  requirements/coverage.in
  requirements/coverage.txt
  requirements/fuzzing.txt
  requirements/tools.txt
  tooling/src/hypothesistooling/__main__.py
Labels: tests/build/CI

#3946 Allow excluding `NaT`
  hypothesis-python/RELEASE.rst
  hypothesis-python/setup.py
  hypothesis-python/src/hypothesis/extra/numpy.py
  hypothesis-python/src/hypothesis/vendor/tlds-alpha-by-domain.txt
  hypothesis-python/tests/numpy/test_from_dtype.py
Labels: enhancement
