Repository HypothesisWorks/hypothesis, pull requests merged in 2024-01, with the labels that each got.

#3839 Allow `from_regex(..., alphabet=...)` to exclude branches; add `alphabet=` to `from_lark()`
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/extra/lark.py
  hypothesis-python/src/hypothesis/strategies/_internal/regex.py
  hypothesis-python/tests/cover/test_direct_strategies.py
  hypothesis-python/tests/lark/test_grammar.py
Labels: new-feature

#3852 Generate empty flag enums
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/internal/compat.py
  hypothesis-python/src/hypothesis/strategies/_internal/core.py
  hypothesis-python/tests/conjecture/test_float_encoding.py
  hypothesis-python/tests/cover/test_compat.py
  hypothesis-python/tests/cover/test_composite.py
  hypothesis-python/tests/cover/test_lookup.py
  hypothesis-python/tests/cover/test_sampled_from.py
  hypothesis-python/tests/nocover/test_regex.py
  hypothesis-python/tests/nocover/test_sampled_from.py
Labels: enhancement

#3862 Avoid pointless discards during the `reuse` and `target` phases
  hypothesis-python/RELEASE.rst
  hypothesis-python/src/hypothesis/core.py
  hypothesis-python/src/hypothesis/internal/conjecture/engine.py
  hypothesis-python/src/hypothesis/internal/conjecture/pareto.py
  hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py
Labels: performance, legibility
